#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

MATTERMOST_VERSION="5.29.0"

echo "* Setup tmpdir for illumos"
export TMPDIR=/var/tmp

echo "* Setup mattermost user and group"
groupadd -g 1100 mattermost
useradd -m -s /usr/bin/bash -d /home/mattermost -u 1100 -g mattermost mattermost
passwd -N mattermost
passwd -d mattermost

echo "* Build mattermost server";
cd /home/mattermost
git clone https://github.com/mattermost/mattermost-server.git
cd /home/mattermost/mattermost-server/vendor/github.com/fsnotify/fsnotify/
patch -t -N < /opt/local/patches/fen.go.patch 2>&1 1>/dev/null || true
cd /home/mattermost/mattermost-server
export GOPATH=/home/mattermost/go
env GOOS=solaris GOARCH=amd64 /opt/local/bin/go install ./...
cp /home/mattermost/go/bin/* /opt/local/bin/

echo "* Include mattermost webapp";
cd /home/mattermost
# get team-version (not the enterprise-version!) from here:
# https://github.com/mattermost/docs/blob/master/source/administration/version-archive.rst
curl -s -L -O "https://download.qutic.com/src/mattermost/mattermost-team-$MATTERMOST_VERSION-linux-amd64.tar.gz"
tar xf mattermost-team-$MATTERMOST_VERSION-linux-amd64.tar.gz
mkdir -p /home/mattermost/mattermost/data
mkdir -p /home/mattermost/mattermost/client/plugins

echo "* Setup mattermost config";
mv /home/mattermost/mattermost/config/config.json /home/mattermost/mattermost/config/config.json.bak
OUTPUT_CONFIG=/home/mattermost/mattermost/config/config.json config_generator

echo "* Setup user and group rights for mattermost";
chown -R mattermost:mattermost /home/mattermost/mattermost

# Clean up
echo "* Cleaning up."
rm /root/customize
rm -rf  /opt/local/patches
rm -rf /home/mattermost/mattermost-server
rm -rf /home/mattermost/mattermost/bin
rm -rf /home/mattermost/mattermost/prepackaged_plugins/*
rm /home/mattermost/mattermost-team-$MATTERMOST_VERSION-linux-amd64.tar.gz

pkgin -y rm gcc7 go gmake patch

# Prepare image for provisioning
sm-prepare-image -y
